---
galaxy_info:
  author: Minecraft Server
  description: Minecraft サーバーセットアップロール
  company: Your Company
  license: license (MIT)
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - all

dependencies: []
