name: CI for terraform
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
    paths:
      - "*"
      - ".github/workflows/ci_terraform.yml"
      - "!terraform/README.md"

env:
  env: ${{ github.base_ref == 'main' && 'prod' || 'dev' }}
  environment: ${{ github.base_ref == 'main' && 'production' || 'development' }}
  AWS_PROFILE_ACCOUNT: default
  AWS_REGION: ap-northeast-1
  TERRAFORM_VERSION: 1.15.5
  TFCMT_VERSION: 4.14.15
  TFLINT_VERSION: 0.63.1

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  check:
    name: check ${{ github.base_ref == 'main' && 'production' || 'development' }}
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref == 'main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.3
        with:
          ref: ${{ github.head_ref }}

      - name: Terraform setup
        uses: ./.github/actions/setup
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          tfcmt_version: v${{ env.TFCMT_VERSION }}
          aws_role_arn: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_profile: ${{ env.AWS_PROFILE_ACCOUNT }}
          region: ${{ env.AWS_REGION }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6.2.2
        with:
          tflint_version: v${{ env.TFLINT_VERSION }}

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform TFLint
        run: |
          tflint --init
          tflint --config=${{ github.workspace }}/.tflint.hcl --recursive

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          commit_message: "chore: auto format by CI"
          file_pattern: "*"

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          output-file: README.md
          output-method: inject
          git-push: "true"
          recursive: "true"
          recursive-path: modules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  plan:
    needs: check
    name: plan ${{ github.base_ref == 'main' && 'production' || 'development' }}
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref == 'main' && 'prod' || 'dev' }}

    defaults:
      run:
        working-directory: env/${{ github.base_ref == 'main' && 'prd' || 'dev' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.3

      - name: Terraform setup
        uses: ./.github/actions/setup
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          tfcmt_version: v${{ env.TFCMT_VERSION }}
          aws_role_arn: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_profile: ${{ env.AWS_PROFILE_ACCOUNT }}
          region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: tfcmt -var 'target:${{ env.environment }}' plan -patch -- terraform plan -no-color
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_ssh_ip: ${{ secrets.SSH_IP }}
          TF_VAR_slack_channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          TF_VAR_slack_team_id: ${{ secrets.SLACK_TEAM_ID }}
          TF_VAR_slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
